validates:
  email_maximum: 140
  name_maximum: 140
  password_minimum: 6
remember_me_checked: 1
users:
  per_page: 10
gravatar_size: 80
gravatar_tiny_size: 40
gravatar_large_size: 180
gravatar_huge_size: 264
expired_time: 2
name_category_maximum: 50
description_minimum: 10
show: 10
show_rooms: 9
default_image: "https://grandcasinomn.com/files/1615/2208/9595/HK_HotelRoom_Web_200x200.jpg"
room_image_mini_size: "80x80"
room_image_medium_size: "120x120"
room_image_normal_size: "280x280"
zero: 0
rating_form_size: "15x8"
image_quantity: 4
min_times: 30
requests_show: 3
notifications:
  per_page: 5
